### ISSUE TITLE
Show balance when an account is selected

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/accounting#1]
We need to show the bank/ledger balance in any expense/income once selected.

**on expense/income form**
<img width="303" alt="screenshot at jan 15 14-47-28" src="https://cloud.githubusercontent.com/assets/153669/12349103/33cf5d88-bb97-11e5-838c-e709db598375.png">

**on balance transfer**
<img width="278" alt="screenshot at jan 15 14-48-12" src="https://cloud.githubusercontent.com/assets/153669/12349113/4ad8e7c4-bb97-11e5-94ab-d7b810a00b8c.png">

**Comment by asaquzzaman** [comment]
After finish dashboard task i will check this issue.
