### ISSUE TITLE
Can't put more then 2 number in Unit Price

### ISSUE THREAD

**Issue by aamahin** [wp-erp/accounting#22]
I just try to add a sales record but when i try to put the unit price 250 i can't, its don't put me more then 2 number 25 is OK but when i enter 250 its become 2. I think its a bug. Its happen in all unit price, debit, credit,  input box.

Thanks

**Comment by asaquzzaman** [comment]
Please goto 'ERP Settings->Settings' now chose accounting tab and save changes the currency options with the default value.

**Comment by aamahin** [comment]
Thank you, Its worked
