### ISSUE TITLE
Sales transaction donut chart error

### ISSUE THREAD

**Issue by tareq1988** [wp-erp/accounting#7]
<img width="1099" alt="screen shot 2016-01-28 at 7 50 43 pm" src="https://cloud.githubusercontent.com/assets/153669/12646149/8f164b46-c5f8-11e5-8088-96b478dac285.png">

See, there is one invoice and a partial payment was made to that invoice. So the graph should only show **1 Partial**. But its showing 1 partial, 1 paid and 1 overdue.

**Comment by asaquzzaman** [comment]
Has solved this issue
